### ISSUE TITLE
1-Beginner/Personal-Skills/07-How-to-Optimize-Loops 번역에 대한 도움 요청 

### ISSUE THREAD

**Issue by soheekim911** [ohahohah/HowToBeAProgrammer#7]
안녕하세요. 
`How-to-Optimize-Loops`를 번역하던 중, 해석이 어려운 부분을 만나 도움을 구하고자 합니다. 
원문에서 글머리 기호로 표시된 리스트 중 
- `Fold constants together.`
- `Try not to divide.` 

두 문장입니다.

첫번째 문장은 검색을 통해 `constant folding`이라고 불리는 compiler optimization 방법이란 것은 알았는데, 한국어로 검색했을 때도 '상수 폴딩'이라 해석하거나 'constant folding' 그대로 쓴 [검색 결과](https://www.google.com/search?q=constant+folding&sxsrf=ALeKk0399aC8F06Ye2JdvnPaNZ50jPsCbQ:1607928716526&source=lnt&tbs=lr:lang_1ko&lr=lang_ko&sa=X&ved=2ahUKEwiLw-Of8cztAhXbdd4KHVykAWYQpwV6BAgEEB8&biw=683&bih=634)가 몇 개 나오는 정도라서, 이를 `상수 폴딩(constant folding)을 이용합니다` 라고 해야할지, 혹은 좀 더 자세히 그 방식을 기술해야 할지 고민됩니다. 

두번째 문장은 그대로 해석하면 나눗셈을 지양하라는 것 같은데 성능과 관련하여 쓰이는 다른 맥락이 있을까 하여 질문드립니다. 

감사합니다.

**Comment by syohnet** [comment]
안녕하세요, 좋은 주제를 던져주셔서 감사합니다. 
번역하고 계신 글의 원문 [1-Beginner/Personal-Skills/07-How-to-Optimize-Loops](https://github.com/ohahohah/HowToBeAProgrammer/blob/kr/en/1-Beginner/Personal-Skills/07-How-to-Optimize-Loops.md) 을 읽어 보았습니다. 

1. `constant folding`
- 용어로서는 `constant folding` 을 더 많이 사용하는 듯합니다. 
도서 [박수현.Thinking about C/C++ : 프로그래머가 몰랐던 프로그램의 동작 원리.한빛미디어.2014 ](http://preview.hanbit.co.kr/2695/sample_ebook.pdf) 의  11페이지 '2.3 컴파일러 최적화 기법에서 발생하는 문제' 에서 볼 수 있듯이 그 자체를 해석하기 보다 용어처럼 자주 쓰이는 경우가 있는 듯합니다. 

- 여기서는  `constant folding` 그 자체로 표기하기보다 '상수의 연산을 미리 하라'고 번역해도 되지 않을까 싶습니다. 원문에서는 컴파일러의 constant folding 보다 단순히 두 상수인 10 *20 의 계산식을 사용하는 대신 200 이라는 값을 미리 계산해서 적으라는 의미로 파악됩니다. 필요하다면, 역주를 덧붙여도 되지 않을까요?

2. `Try not to divide` 
원문이 짧기 때문에 그 맥락을 정확히 파악하는데는 어려움이 있습니다. 저는 loop 안에 반복적으로 실행할 명령어들 중에 divide 를 피하라 로 이해했습니다. 프로그래밍 언어마다 차이는 있으리라 생각됩니다만 '나눗셈을 하는 것보다 소수 곱셈이 성능상 더 빠르다' 라는 오래된 잘 알려진 격언이 있습니다. 이에 관련해서는 아래 글이 도움이 되시리라 판단됩니다. 
[RPG Cafe: Which is better? Divide by 2 or multiply by 0.5?, Modified date: 15 January 2020 ](https://www.ibm.com/support/pages/which-better-divide-2-or-multiply-05)

덧붙여, 해당 맥락의 정확한 의미에 대해서는 아래 원 repo 의 issue 에서 discussion 을 해보는 것도 좋을 듯합니다. 
https://github.com/braydie/HowToBeAProgrammer/issues

감사합니다.

**Comment by soheekim911** [comment]
상세히 답변해주셔서 정말 감사합니다! 

1번에 대해서는 말씀대로 풀어서 쓰고, 역주에 자세한 내용은 constant folding을 찾아보라고 키워드를 적어보겠습니다.
2번은 올려주신 아티클을 읽어보았고, 같은 결과를 내기 위해서 나눗셈보다 곱하기 연산이 좀 더 빠르고 정확한 것이 어느 정도 알려진 사실이라면 문장을 직역해도 될 것 같다고 판단했습니다.

역주를 어떤 형식으로 달아야 할까 고민했는데 https://github.com/javascript-tutorial/ko.javascript.info/issues/265 <- 이 번역 프로젝트에서는 비슷한 고민에 대해 (옮긴이 설명 ~~  - `옮긴이`) 로 표기했네요. github markdown에서 각주를 따로 제공하는 것 같지 않아서 일단 같은 형식으로 달아볼까 합니다. 

이 내용을 바탕으로 갈무리하여 PR하도록 하겠습니다.

**Comment by syohnet** [comment]
기여에 감사드립니다. 본 issue 는 종료하겠습니다. :)
